# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 12:32
from __future__ import unicode_literals

import autoslug.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Tytuł')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('body', models.TextField(verbose_name='Tekst')),
                ('published', models.BooleanField(default=False, verbose_name='Opublikowany')),
            ],
            options={
                'verbose_name': 'Artykuł',
                'verbose_name_plural': 'Artykuły',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_prefix', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tytuł')),
                ('full_name', models.CharField(max_length=80, verbose_name='Imię i nazwisko')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='full_name', unique=True)),
                ('order', models.DecimalField(decimal_places=0, default=999, max_digits=3, verbose_name='W kolejności')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Krótki opis')),
                ('avatar', models.ImageField(blank=True, default='avatars/no-avatar', null=True, upload_to='avatars/author/', verbose_name='Zdjęcie')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autorzy',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nazwa')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Colleague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_prefix', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tytuł')),
                ('full_name', models.CharField(max_length=80, verbose_name='Imię i nazwisko')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='full_name', unique=True)),
                ('order', models.DecimalField(decimal_places=0, default=999, max_digits=3, verbose_name='W kolejności')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Krótki opis')),
                ('function', models.CharField(blank=True, max_length=40, null=True, verbose_name='Stanowisko')),
                ('avatar', models.ImageField(blank=True, default='avatars/no-avatar', null=True, upload_to='avatars/colleague/', verbose_name='Zdjęcie')),
            ],
            options={
                'verbose_name': 'Współpracownik',
                'verbose_name_plural': 'Współpracownicy',
            },
        ),
        migrations.CreateModel(
            name='CustomFlatPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='link_name', unique=True, verbose_name='Link')),
                ('name', models.CharField(help_text='Używana w menu po lewej stronie np. Kontakt', max_length=30, verbose_name='Nazwa linku')),
                ('title', models.CharField(max_length=70, verbose_name='Tytuł')),
                ('body', models.TextField(verbose_name='Tekst')),
                ('order', models.DecimalField(blank=True, decimal_places=0, default=99, max_digits=2, null=True)),
                ('visible_on_nav', models.BooleanField(default=True, verbose_name='Pokazuj w menu')),
                ('visible_on_footer', models.BooleanField(default=True, verbose_name='Pokazuj w stópce')),
            ],
            options={
                'verbose_name': 'Dodatkowa strona',
                'verbose_name_plural': 'Dodatkowe strony',
                'ordering': ('-order',),
            },
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_prefix', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tytuł')),
                ('full_name', models.CharField(max_length=80, verbose_name='Imię i nazwisko')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='full_name', unique=True)),
                ('order', models.DecimalField(decimal_places=0, default=999, max_digits=3, verbose_name='W kolejności')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Krótki opis')),
                ('function', models.CharField(blank=True, max_length=40, null=True, verbose_name='Stanowisko')),
                ('avatar', models.ImageField(blank=True, default='avatars/no-avatar', null=True, upload_to='avatars/editor/', verbose_name='Zdjęcie')),
            ],
            options={
                'verbose_name': 'Redaktor',
                'verbose_name_plural': 'Redaktorzy',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tytuł')),
                ('date', models.IntegerField(validators=[django.core.validators.RegexValidator(regex='^20\\d{2}$')], verbose_name='Rocznik')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('cover', models.ImageField(blank=True, default='issues/no-img.png', null=True, upload_to='issues/', verbose_name='Okładka')),
                ('index_page_visible', models.BooleanField(default=False, verbose_name='Wyświetlaj na stronie głównej')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Krótki opis')),
                ('alternative_link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alternatywny link')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Tytuł')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('body', models.TextField(verbose_name='Tekst')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Stworzony dnia')),
                ('categories', models.ManyToManyField(blank=True, to='mainapp.Category', verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'Newsy',
                'ordering': ('pk',),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(blank=True, to='mainapp.Author', verbose_name='Autorzy'),
        ),
        migrations.AddField(
            model_name='article',
            name='belong_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Issue', verbose_name='Numer'),
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, to='mainapp.Category', verbose_name='Kategorie'),
        ),
    ]
