# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 11:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'verbose_name': 'Numer', 'verbose_name_plural': 'Numery'},
        ),
        migrations.AlterField(
            model_name='issue',
            name='date',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(regex='^20\\d{2}$')], verbose_name='Rocznik'),
        ),
    ]
