# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20171115_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customflatpage',
            options={'ordering': ('order',), 'verbose_name': 'Dodatkowa strona', 'verbose_name_plural': 'Dodatkowe strony'},
        ),
        migrations.RenameField(
            model_name='customflatpage',
            old_name='visible_on_nav',
            new_name='visible_on_sidebar',
        ),
    ]
