# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20171117_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='belong_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.Issue', verbose_name='Numer'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=tinymce.models.HTMLField(verbose_name='Tekst'),
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='colleague',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='customflatpage',
            name='body',
            field=tinymce.models.HTMLField(verbose_name='Tekst'),
        ),
        migrations.AlterField(
            model_name='editor',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=tinymce.models.HTMLField(verbose_name='Tekst'),
        ),
    ]
