# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20171117_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2017-11-11', verbose_name='Stworzony dnia'),
            preserve_default=False,
        ),
    ]
